// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year  int32  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Color string `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Price string `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Stock int32  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Car) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Car) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Car) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Car) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddCarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car *Car `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
}

func (x *AddCarRequest) Reset() {
	*x = AddCarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCarRequest) ProtoMessage() {}

func (x *AddCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCarRequest.ProtoReflect.Descriptor instead.
func (*AddCarRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *AddCarRequest) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

type AddCarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddCarResponse) Reset() {
	*x = AddCarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCarResponse) ProtoMessage() {}

func (x *AddCarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCarResponse.ProtoReflect.Descriptor instead.
func (*AddCarResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *AddCarResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCarRequest) Reset() {
	*x = GetCarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarRequest) ProtoMessage() {}

func (x *GetCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarRequest.ProtoReflect.Descriptor instead.
func (*GetCarRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetCarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize   int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNumber int32 `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
}

func (x *ListCarsRequest) Reset() {
	*x = ListCarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsRequest) ProtoMessage() {}

func (x *ListCarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsRequest.ProtoReflect.Descriptor instead.
func (*ListCarsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ListCarsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCarsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type ListCarsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car       []*Car `protobuf:"bytes,1,rep,name=car,proto3" json:"car,omitempty"`
	TotalCars int32  `protobuf:"varint,2,opt,name=total_cars,json=totalCars,proto3" json:"total_cars,omitempty"`
}

func (x *ListCarsResponse) Reset() {
	*x = ListCarsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsResponse) ProtoMessage() {}

func (x *ListCarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsResponse.ProtoReflect.Descriptor instead.
func (*ListCarsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ListCarsResponse) GetCar() []*Car {
	if x != nil {
		return x.Car
	}
	return nil
}

func (x *ListCarsResponse) GetTotalCars() int32 {
	if x != nil {
		return x.TotalCars
	}
	return 0
}

type UpdateCarStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StockChange int32  `protobuf:"varint,2,opt,name=stock_change,json=stockChange,proto3" json:"stock_change,omitempty"`
}

func (x *UpdateCarStockRequest) Reset() {
	*x = UpdateCarStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCarStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarStockRequest) ProtoMessage() {}

func (x *UpdateCarStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateCarStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCarStockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCarStockRequest) GetStockChange() int32 {
	if x != nil {
		return x.StockChange
	}
	return 0
}

type UpdateCarStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewStock int32 `protobuf:"varint,1,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
}

func (x *UpdateCarStockResponse) Reset() {
	*x = UpdateCarStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCarStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarStockResponse) ProtoMessage() {}

func (x *UpdateCarStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateCarStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCarStockResponse) GetNewStock() int32 {
	if x != nil {
		return x.NewStock
	}
	return 0
}

var File_proto_inventory_inventory_proto protoreflect.FileDescriptor

var file_proto_inventory_inventory_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x95, 0x01, 0x0a,
	0x03, 0x43, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x22, 0x31, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43,
	0x61, 0x72, 0x52, 0x03, 0x63, 0x61, 0x72, 0x22, 0x20, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x53, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x03, 0x63, 0x61,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x61, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x73,
	0x22, 0x4a, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x32, 0xa1, 0x02, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x43,
	0x61, 0x72, 0x12, 0x18, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x41,
	0x64, 0x64, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x12, 0x18, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x43, 0x61, 0x72, 0x12, 0x43, 0x0a, 0x08, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x55, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x64, 0x65, 0x61, 0x6c, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_inventory_proto_rawDescData = file_proto_inventory_inventory_proto_rawDesc
)

func file_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_inventory_inventory_proto_rawDescData)
	})
	return file_proto_inventory_inventory_proto_rawDescData
}

var file_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_inventory_inventory_proto_goTypes = []any{
	(*Car)(nil),                    // 0: inventory.Car
	(*AddCarRequest)(nil),          // 1: inventory.AddCarRequest
	(*AddCarResponse)(nil),         // 2: inventory.AddCarResponse
	(*GetCarRequest)(nil),          // 3: inventory.GetCarRequest
	(*ListCarsRequest)(nil),        // 4: inventory.ListCarsRequest
	(*ListCarsResponse)(nil),       // 5: inventory.ListCarsResponse
	(*UpdateCarStockRequest)(nil),  // 6: inventory.UpdateCarStockRequest
	(*UpdateCarStockResponse)(nil), // 7: inventory.UpdateCarStockResponse
}
var file_proto_inventory_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.AddCarRequest.car:type_name -> inventory.Car
	0, // 1: inventory.ListCarsResponse.car:type_name -> inventory.Car
	1, // 2: inventory.InventoryService.AddCar:input_type -> inventory.AddCarRequest
	3, // 3: inventory.InventoryService.GetCar:input_type -> inventory.GetCarRequest
	4, // 4: inventory.InventoryService.ListCars:input_type -> inventory.ListCarsRequest
	6, // 5: inventory.InventoryService.UpdateCarStock:input_type -> inventory.UpdateCarStockRequest
	2, // 6: inventory.InventoryService.AddCar:output_type -> inventory.AddCarResponse
	0, // 7: inventory.InventoryService.GetCar:output_type -> inventory.Car
	5, // 8: inventory.InventoryService.ListCars:output_type -> inventory.ListCarsResponse
	7, // 9: inventory.InventoryService.UpdateCarStock:output_type -> inventory.UpdateCarStockResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_inventory_inventory_proto_init() }
func file_proto_inventory_inventory_proto_init() {
	if File_proto_inventory_inventory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_inventory_inventory_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddCarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddCarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetCarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListCarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListCarsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCarStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateCarStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_inventory_inventory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_inventory_proto = out.File
	file_proto_inventory_inventory_proto_rawDesc = nil
	file_proto_inventory_inventory_proto_goTypes = nil
	file_proto_inventory_inventory_proto_depIdxs = nil
}
